stages:
  - test
  - build
  - deploy


.test application:
  image: node:16.13.2-alpine
  stage: test
  script:
    - npm install
    - npm test

.build-container:
  stage: build
  services:
   - name: docker:20.10.16-dind
     alias: dockerdaemon
  image: docker:20
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY_USER
    - docker build -t $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG .
    - docker logout
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG

deploy application:
  stage: deploy
  image: node:16-alpine3.15
  script:
    - apk add --update openssh-client bash
    - echo $SSH_PRIVATE_KEY
    - eval $(ssh-agent -s)
    # - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Configuring known hosts based on the CI Variable `KNOWN_HOSTS`"
    - |
      [[ ! -z "$KNOWN_HOSTS" ]] && echo "$KNOWN_HOSTS" | xargs -n 1 -I '{}' ssh-keyscan '{}' >> ~/.ssh/known_hosts || echo "KNOWN_HOSTS not set"
    - chmod 644 ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    # - ssh-keyscan 165.22.75.102
    # - ssh-keyscan -T 240 165.22.75.102 >> ~/.ssh/known_hosts
    # - ssh-keyscan -H '165.22.75.102' >> ~/.ssh/known_hosts
    - ssh root@165.22.75.102 ls

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    # - git config --global user.email "user@example.com"
    # - git config --global user.name "User name"
