stages:
  - test
  - build
  - deploy

image: node:16.13.2-alpine

test application:
  stage: test
  script:
    - npm install
    - npm start
    - apk update
    - apk add curl
    - curl https://jsonplaceholder.typicode.com/users

build application:
  stage: build
  script:
    - echo "My first gitlab pipeline!" > file.txt
    - cat file.txt

deploy application:
  stage: deploy
  script:
    - echo "My first gitlab pipeline!" > file.txt
    - cat file.txt
