variables:
  RULES_CHANGES_PATH: "**/*"

.per-project-changes:
  rules:
    changes:
      - $RULES_CHANGES_PATH

account:
  extends: .per-project-changes
  variables:
    CHILD_PIPELINE_EXECUTION_CONTEXT: "accounts-microservice"
    RULES_CHANGES_PATH: "accounts-microservice/**/*"
  trigger:
    include: .sub-gitlab-ci.yml
    strategy: depend

auth:
  extends: .per-project-changes
  variables:
    CHILD_PIPELINE_EXECUTION_CONTEXT: "auth-microservice"
    RULES_CHANGES_PATH: "auth-microservice/**/*"
  trigger:
    include: .sub-gitlab-ci.yml
    strategy: depend
