stages:
  - test
  - build
  - deploy

# image: node:16.13.2-alpine

# test application:
#   stage: test
#   script:
#     - npm install
#     - npm run test

build-container:
  stage: build
  services:
    - docker:20.10.16-dind
  image: docker:20
  script:
    - docker --version
    - docker build -t $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
    - docker push $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG
    - echo "done!"

deploy application:
  stage: deploy
  script:
    - echo "My first gitlab pipeline!" > file.txt
    - cat file.txt
