stages:
  - test
  - build
  - deploy

test-application:
  image: node:16.13.2-alpine
  stage: test
  script:
    - npm install
    - npm test

build-container:
  stage: build
  services:
   - name: docker:20.10.16-dind
     alias: dockerdaemon
  image: docker:20
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY_USER
    - docker build -t $DOCKER_HUB_REPO:$CI_COMMIT_SHA .
    - docker logout
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_HUB_REPO:$CI_COMMIT_SHA

deploy-application:
  stage: deploy
  image: node:16-alpine3.15
  script:
    - apk add --update openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey $DEPLOY_USER@$DEPLOY_HOST "echo $CI_REGISTRY_PASSWORD | sudo docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY; docker run -p 3000:3000 -t $DOCKER_HUB_REPO:$CI_COMMIT_SHA"
