before_script:
    - "echo Running child pipeline in subdirectory: $CHILD_PIPELINE_EXECUTION_CONTEXT"
    - cd $CHILD_PIPELINE_EXECUTION_CONTEXT

include: $CHILD_PIPELINE_EXECUTION_CONTEXT/.gitlab-ci.yml
