version: '3.8'

services:
  auth:
    container_name: auth
    # image: auth:$TAG_NAME
    build:
      context: ./auth-microservice
    ports:
      - 4000:4000
    networks:
      - bankApp-network
    volumes:
      - ./auth-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  account:
    container_name: account
    build:
      context: ./accounts-microservice
    ports:
      - 3000:3000
    networks:
      - bankApp-network
    volumes:
      - ./accounts-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  bankApp-network: