apiVersion: v1
kind: Service
metadata:
  name: accounts-microservice
spec:
  selector:
    app: accounts-microservice
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-microservice
  template:
    metadata:
      labels:
        app: accounts-microservice
    spec:
      containers:
        - name: accounts-microservice
          image: accounts-microservice
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: auth-microservice
spec:
  selector:
    app: auth-microservice
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
        - name: auth-microservice
          image: {{TAG_NAME}}
          imagePullPolicy: Never
          ports:
            - containerPort: 4000