include: 
  local: '/infra/.commons-gitlab-ci.yml'

variables:
  TAG_NAME: $DOCKER_HUB_REPO_AUTH:$CI_COMMIT_REF_SLUG
  APP_NAME: auth-microservice
  PORT: 4000

test-application:
  extends: .test-node-app

build-application:
  needs: ["test-application"]
  extends: .build-node-app

deploy-application:
  needs: ["build-application"]
  extends: .deploy-node-app
