include: 
  local: '/infra/.commons-gitlab-ci.yml'

test-application:
  extends: .test-node-app

build-application:
  needs: ["test-application"]
  extends: .build-node-app
  variables:
    TAG_NAME: $DOCKER_HUB_REPO_AUTH:$CI_COMMIT_REF_SLUG