apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
spec:
  selector:
    app: <APP_NAME>
  ports:
    - port: <APP_PORT>
      targetPort: 4000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <APP_NAME>
          image: <TAG_NAME>
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
