check-should-run:
  script: echo "Default text"
  only:
    changes:
      - "**/*"

test-application:
  stage: test
  image: node:16.13.2-alpine
  needs: ['check-should-run']
  script:
    - npm install
    - npm test

# build-container:
#   stage: build
#   services:
#    - name: docker:20.10.16-dind
#      alias: dockerdaemon
#   image: docker:20
#   variables:
#     # Tell docker CLI how to talk to Docker daemon.
#     DOCKER_HOST: tcp://dockerdaemon:2375/
#     # Use the overlayfs driver for improved performance.
#     DOCKER_DRIVER: overlay2
#     # Disable TLS since we're running inside local network.
#     DOCKER_TLS_CERTDIR: ""
#     TAG_NAME: $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG
#   script:
#     - docker info
#     - echo $CI_REGISTRY_PASSWORD
#     - echo $CI_REGISTRY_USER
#     - >
#       docker build
#       --pull
#       --cache-from $TAG_NAME
#       --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
#       --label "org.opencontainers.image.url=$CI_PROJECT_URL"
#       --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
#       --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
#       --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
#       --tag $TAG_NAME .
      
#     - docker logout
#     - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
#     - docker push $TAG_NAME

# deploy-application:
#   stage: deploy
#   needs: ["build-container"]
#   image: node:16-alpine3.15
#   variables:
#     TAG_NAME: $DOCKER_HUB_REPO:$CI_COMMIT_REF_SLUG
#   script:
#     - apk add --update openssh-client bash
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - >
#       ssh
#       -o StrictHostKeyChecking=no
#       -o PreferredAuthentications=publickey
#       $DEPLOY_USER@$DEPLOY_HOST
#       "echo $CI_REGISTRY_PASSWORD | sudo docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY; docker pull $TAG_NAME; docker stop $CI_COMMIT_REF_NAME; docker rm $CI_COMMIT_REF_NAME; docker run -p 3000:3000 --name $CI_COMMIT_REF_NAME -d -t $TAG_NAME"
